# Generated by Django 4.1.6 on 2023-05-29 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registradores', '0003_remove_status_mail_propietario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status_mail',
            old_name='envido',
            new_name='enviado',
        ),
    ]
