# Generated by Django 4.1.6 on 2023-05-30 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registradores', '0004_rename_envido_status_mail_enviado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MiModelo',
        ),
    ]
