# Generated by Django 4.1.6 on 2023-05-30 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smtp', '0005_enviados_estatus'),
        ('registradores', '0005_delete_mimodelo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status_PC',
            new_name='Estatus_Mail',
        ),
        migrations.RenameModel(
            old_name='Status_Web',
            new_name='Estatus_PC',
        ),
        migrations.RenameModel(
            old_name='Status_Mail',
            new_name='Estatus_Web',
        ),
    ]
