# Generated by Django 4.1.6 on 2023-05-30 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smtp', '0006_remove_enviados_estatus_delete_credenciales'),
        ('registradores', '0006_rename_status_pc_estatus_mail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estatus_pc',
            name='estado_consola',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Credenciales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=25)),
                ('contraseña', models.CharField(max_length=25)),
                ('enviado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smtp.enviados')),
            ],
        ),
        migrations.AddField(
            model_name='estatus_pc',
            name='credenciales',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registradores.credenciales'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estatus_web',
            name='credenciales',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registradores.credenciales'),
            preserve_default=False,
        ),
    ]
