# Generated by Django 4.1.6 on 2023-05-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registradores', '0007_estatus_pc_estado_consola_credenciales_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('request_method', models.CharField(blank=True, max_length=10, null=True)),
                ('query_params', models.TextField(blank=True, null=True)),
                ('os_info', models.CharField(blank=True, max_length=100, null=True)),
                ('device_info', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='estatus_mail',
            name='country',
        ),
        migrations.RemoveField(
            model_name='estatus_mail',
            name='device_info',
        ),
        migrations.RemoveField(
            model_name='estatus_mail',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='estatus_mail',
            name='language',
        ),
        migrations.RemoveField(
            model_name='estatus_mail',
            name='os_info',
        ),
        migrations.RemoveField(
            model_name='estatus_mail',
            name='query_params',
        ),
        migrations.RemoveField(
            model_name='estatus_mail',
            name='request_method',
        ),
        migrations.RemoveField(
            model_name='estatus_mail',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='estatus_mail',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='estatus_pc',
            name='country',
        ),
        migrations.RemoveField(
            model_name='estatus_pc',
            name='device_info',
        ),
        migrations.RemoveField(
            model_name='estatus_pc',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='estatus_pc',
            name='language',
        ),
        migrations.RemoveField(
            model_name='estatus_pc',
            name='os_info',
        ),
        migrations.RemoveField(
            model_name='estatus_pc',
            name='query_params',
        ),
        migrations.RemoveField(
            model_name='estatus_pc',
            name='request_method',
        ),
        migrations.RemoveField(
            model_name='estatus_pc',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='estatus_pc',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='estatus_web',
            name='country',
        ),
        migrations.RemoveField(
            model_name='estatus_web',
            name='device_info',
        ),
        migrations.RemoveField(
            model_name='estatus_web',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='estatus_web',
            name='language',
        ),
        migrations.RemoveField(
            model_name='estatus_web',
            name='os_info',
        ),
        migrations.RemoveField(
            model_name='estatus_web',
            name='query_params',
        ),
        migrations.RemoveField(
            model_name='estatus_web',
            name='request_method',
        ),
        migrations.RemoveField(
            model_name='estatus_web',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='estatus_web',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='estatus_web',
            name='estatus',
            field=models.BooleanField(default=False),
        ),
    ]
