# Generated by Django 4.1.6 on 2023-05-30 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registradores', '0008_registro_remove_estatus_mail_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='query_params',
            new_name='agente',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='country',
            new_name='dispositivo',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='timestamp',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='device_info',
            new_name='idioma',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='ip_address',
            new_name='ip',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='request_method',
            new_name='metodo',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='language',
            new_name='pais',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='user_agent',
            new_name='parametros',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='os_info',
            new_name='sistema_operativo',
        ),
        migrations.AddField(
            model_name='estatus_mail',
            name='registro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registradores.registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estatus_pc',
            name='registro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registradores.registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estatus_web',
            name='registro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registradores.registro'),
            preserve_default=False,
        ),
    ]
