# Generated by Django 4.1.6 on 2023-05-30 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registradores', '0009_rename_query_params_registro_agente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatus_pc',
            name='credenciales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registradores.credenciales'),
        ),
        migrations.AlterField(
            model_name='estatus_web',
            name='credenciales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registradores.credenciales'),
        ),
    ]
