# Generated by Django 4.1.6 on 2023-05-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registradores', '0010_alter_estatus_pc_credenciales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estatus_mail',
            name='registro',
        ),
        migrations.RemoveField(
            model_name='estatus_pc',
            name='registro',
        ),
        migrations.RemoveField(
            model_name='estatus_web',
            name='registro',
        ),
        migrations.AddField(
            model_name='estatus_mail',
            name='agente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estatus_mail',
            name='dispositivo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estatus_mail',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estatus_mail',
            name='idioma',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estatus_mail',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estatus_mail',
            name='metodo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='estatus_mail',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estatus_mail',
            name='parametros',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estatus_mail',
            name='sistema_operativo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estatus_pc',
            name='agente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estatus_pc',
            name='dispositivo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estatus_pc',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estatus_pc',
            name='idioma',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estatus_pc',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estatus_pc',
            name='metodo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='estatus_pc',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estatus_pc',
            name='parametros',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estatus_pc',
            name='sistema_operativo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estatus_web',
            name='agente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estatus_web',
            name='dispositivo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estatus_web',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estatus_web',
            name='idioma',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estatus_web',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estatus_web',
            name='metodo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='estatus_web',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estatus_web',
            name='parametros',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estatus_web',
            name='sistema_operativo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
