# Generated by Django 4.1.6 on 2023-05-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registradores', '0011_remove_estatus_mail_registro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estatus_pc',
            name='credenciales',
        ),
        migrations.AddField(
            model_name='estatus_pc',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
