# Generated by Django 4.1.6 on 2023-05-30 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registradores', '0012_remove_estatus_pc_credenciales_estatus_pc_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estatus_pc',
            old_name='estado_consola',
            new_name='estado_script',
        ),
    ]
