# Generated by Django 4.1.6 on 2023-05-30 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registradores', '0013_rename_estado_consola_estatus_pc_estado_script'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estatus_pc',
            name='estado_script',
        ),
        migrations.RemoveField(
            model_name='estatus_web',
            name='estatus',
        ),
    ]
