# Generated by Django 4.1.6 on 2023-05-30 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registradores', '0014_remove_estatus_pc_estado_script_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credenciales',
            name='enviado',
        ),
        migrations.RemoveField(
            model_name='estatus_web',
            name='credenciales',
        ),
        migrations.AddField(
            model_name='credenciales',
            name='estatus_web',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registradores.estatus_web'),
            preserve_default=False,
        ),
    ]
