# Generated by Django 4.1.6 on 2023-05-30 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0002_plantillas_archivo_plantillas_imagen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantillas',
            old_name='servicio',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='plantillas',
            name='tipo',
            field=models.CharField(choices=[('phishing', 'phishing'), ('credenciales-chrome', 'credenciales-chrome'), ('acceso-remoto', 'acceso-remoto')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plantillas',
            name='archivo',
            field=models.FileField(default=1, upload_to='uploads/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plantillas',
            name='imagen',
            field=models.ImageField(default=1, upload_to='ruta/para/subir/'),
            preserve_default=False,
        ),
    ]
