# Generated by Django 4.1.6 on 2023-05-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0003_rename_servicio_plantillas_nombre_plantillas_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantillas',
            name='archivo',
        ),
        migrations.AddField(
            model_name='plantillas',
            name='script',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plantillas',
            name='tipo',
            field=models.CharField(choices=[('phishing', 'phishing'), ('script', 'script')], max_length=20),
        ),
    ]
