# Generated by Django 4.1.6 on 2023-05-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0004_remove_plantillas_archivo_plantillas_script_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantillas',
            name='script',
            field=models.TextField(blank=True, null=True),
        ),
    ]
