# Generated by Django 4.1.6 on 2023-05-30 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0006_plantillas_propietario_alter_plantillas_emisor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantillas',
            name='propietario',
        ),
    ]
