# Generated by Django 4.1.6 on 2023-05-31 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0009_plantillas_usuario_opcional_alter_plantillas_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantillas',
            name='usuario_opcional',
        ),
    ]
