# Generated by Django 4.1.6 on 2023-05-29 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registradores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plantillas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enviados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('mail_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registradores.status_mail')),
                ('pc_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registradores.status_pc')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantillas.plantillas')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('web_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registradores.status_web')),
            ],
        ),
    ]
