# Generated by Django 4.1.6 on 2023-05-29 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('correos', '0001_initial'),
        ('smtp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviados',
            name='correo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='correos.correos'),
            preserve_default=False,
        ),
    ]
