# Generated by Django 4.1.6 on 2023-05-29 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smtp', '0002_enviados_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enviados',
            name='mail_status_id',
        ),
        migrations.RemoveField(
            model_name='enviados',
            name='pc_status_id',
        ),
        migrations.RemoveField(
            model_name='enviados',
            name='web_status_id',
        ),
    ]
