# Generated by Django 4.1.6 on 2023-05-30 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smtp', '0003_remove_enviados_mail_status_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credenciales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=25)),
                ('contraseña', models.CharField(max_length=25)),
                ('enviado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smtp.enviados')),
            ],
        ),
    ]
