# Generated by Django 4.1.6 on 2023-06-13 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('correos', '0001_initial'),
        ('smtp', '0006_remove_enviados_estatus_delete_credenciales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_acceso', models.DateTimeField(auto_now_add=True)),
                ('puerto', models.CharField(max_length=10)),
                ('estatus', models.BooleanField(default=False)),
                ('correo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='correos.correos')),
                ('enviado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smtp.enviados')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
