# Generated by Django 4.1.6 on 2023-05-30 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emisores',
            name='propietario',
        ),
    ]
